### ISSUE TITLE
Bug : Continuously call insert(...) delete(...) and insert(...)

### ISSUE THREAD

**Issue by liguoying521** [pulyaevskiy/quill-delta-dart#8]
Run :
```dart
main() {
  print(
    Delta()..insert('Hello world .')..delete(1)..insert('!')
  );
}
```
Cause :
```
Unhandled exception:
'package:quill_delta/quill_delta.dart': Failed assertion: line 310 pos 12: 'operation != null && last.key == operation.key': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Delta._mergeWithTail (package:quill_delta/quill_delta.dart:310:12)
#3      Delta.push (package:quill_delta/quill_delta.dart:349:11)
#4      Delta.insert (package:quill_delta/quill_delta.dart:298:5)
#5      main (file:///Users/jekyll/WorkSpace/idea/dart_in_action/bin/quill_delta.dart:5:50)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by cgestes** [comment]
see https://github.com/pulyaevskiy/quill-delta-dart/pull/7 for the fix :)
